### ISSUE TITLE
ARAX Linkout Does Not Describe the ARAX Reasoning

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#342]
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/3b2cd4e0-4112-422b-98db-df05b075d4ae)

needs to have a description of the reasoning of the tool

https://arax.ncats.io/

**Comment by dkoslicki** [comment]
iirc, the UI pulls this from the `primary_knowledge_source` which is accurate. The underlying publication [here](https://www.biorxiv.org/content/10.1101/2022.11.29.518441v2) (GigaScience version in press) would be the _how_ the prediction works. Where should I put this information so the UI knows to display it? Since a publication does not have an `infores` that would resolve to a URL, it would need to go elsewhere, and the UI would need to also pull from that alternative location. @Genomewide thoughts on where it could go?

**Comment by andrewsu** [comment]
Agreed with @dkoslicki that we haven't defined a place to put a link that specifically describes the reasoning method.  Currently, I think the UI is pulling it from the infores catalog under the `xref` key, for example: https://github.com/biolink/biolink-model/blob/master/infores_catalog.yaml#LL45C1-L53C9.  So I think this is a question for the SRI team (@sierra-moxon?) on where a "description of the method" URL might go.

```
- id: infores:arax
  status: released
  name: ARAX Translator Reasoner
  xref:
  - https://arax.ncats.io/
  synonym:
  - ARAX
  description: TRAPI 1.1 endpoint for the NCATS Biomedical Translator Reasoner called
    ARAX
```
Also applies to the related issues for the other ARAs
* https://github.com/NCATSTranslator/Feedback/issues/343
* https://github.com/NCATSTranslator/Feedback/issues/346
* https://github.com/NCATSTranslator/Feedback/issues/344
