### ISSUE TITLE
Might it be useful to have a Feedback convention for embedding Testing Infrastructure "TestAsset" entries in Feedback to assist harvesting of relevant  assets in situ?

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATSTranslator/Feedback#626]
I'm thinking that the Github web API likely does give read access to Issues (just guessing... haven't yet gone looking for the details).  I would imagine that the Issue text comes back as some kind of sequence of Comment objects which are a simple Markdown text blob.

I'm wondering if we were to develop some kind of Markdown friendly annotation convention for embedding formal definitions of test assets` in situ`, that we'd be able to automatically harvest them into a TSV and/or JSON for further capture and test case generation in the system (edited) 

Perhaps this "annotation convention" could be as simple as some kind of embedded multi-line YAML text (see example below).

Note that the [TranslatorTestingModel](https://github.com/TranslatorSRI/TranslatorTestingModel) under development is based on LinkML which has some helpful injected content that could be used in theYAML markup, perhaps "**`class_name: TestAsset`**" that the harvesting code would need to see in order to differentiate TestAsset (or other) testing data from any other YAML used in the issue, for other purposes.

Note that such markup can be added by Feedback test curators after the original Feedback is posted by others not too familiar with the testing model conventions, but would accelerate curation and provide good documentation of tests in their original context: the Feedback issue.

Here's what it might look like this:

### Tests

```yaml
class_name: TestAsset
id: example:TestAsset001
name: TestAsset001
description: Iron treats Aceruloplasminemia
input_id: MONDO:0011426
input_name: Aceruloplasminemia
predicate: Treats
output_id: DRUGBANK:DB01592
output_name: Iron (PUBCHEM)
expected_output: number_4_NeverShow
test_reference: https://github.com/NCATSTranslator/Feedback/issues/506
semantic_severity: NotApplicable
in_v1: True
well_known: False
runner_settings:
  - "inferred"
  - "test"
```
